name: Docker Build

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
    pull_request:
        paths-ignore:
            - 'README.md'

jobs:
    build-final-image:
        name: Build Final Image
        runs-on: ubuntu-latest

        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Metadata for Final Image Build
              id: docker_meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ secrets.DOCKERHUB_USERNAME }}/gohttp:latest
                  flavor: |
                      latest=false
                  tags: |
                      type=raw,value=99

            - name: Docker Build and Push to GHCR and Docker Hub
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
